### ISSUE TITLE
type data complex128 apa itu?

### ISSUE THREAD

**Issue by Muh-Sidik** [pondok-programmer/golang-learn#30]
https://github.com/pondok-programmer/golang-learn/blob/11d8bbe118a6df3632da97770f70e0e62d081976/sidik/basic_11.go#L11

**Comment by muizidn** [comment]
https://github.com/pondok-programmer/golang-learn/pull/31/files/4f4344ddaeb91678c35f24ad623a5530a86a8d45#r374109974
